## Introduction to Tensors
Welcome to your first TensorFlow lesson! Today we're diving into the basics of Tensors, the core components of TensorFlow and deep learning. Tensors are powerful mathematical entities used to represent data across a wide range of dimensions, making them crucial for machine learning and neural networks.

Let's kickstart our journey by learning how to create and work with tensors. This will be our building block for mastering machine learning with TensorFlow.

## Getting Started with TensorFlow
Great, now that we understand a bit about tensors, let's dive into TensorFlow. Simply put, TensorFlow is a free, open-source software library for high-performance numerical computation. It's flexible architecture allows easy deployment of computation across multiple platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices. TensorFlow was originally developed by researchers and engineers working on the Google Brain team within Google's Machine Intelligence Research organization to conduct machine learning and deep neural networks research.

One of the main data structures TensorFlow uses to operate is the tensor — hence, TensorFlow!

Before we proceed, you need to have TensorFlow installed. You can install it using pip by running the following command:

```sh

pip install tensorflow
```
However, you don't need to worry about this in the CodeSignal environment, as all necessary libraries, including TensorFlow, are already set up.

Let's move on to how we can create tensors.

## Creating Tensors in TensorFlow
In TensorFlow, we can easily create tensors using various functions, one of which is tf.constant(). This function allows us to create a tensor with fixed values. It requires at least one argument, which will be the data we are passing in. Additionally, we can also specify the datatype of the elements in the tensor.

In the following code, we use tf.constant() to create a 2x3 matrix with integer values:

```Python

import tensorflow as tf

# Creating a constant tensor
tensor_example = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)

print(tensor_example)
```
The output will look something like this:

```sh

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
```
Here, tf.constant() created a tensor object with a shape of (2,3) and a datatype int32.

## Understanding Tensor Properties
Now that we know how to create a Tensor, let's talk about its properties. Each Tensor has two important properties: a shape and a datatype.

The shape of a tensor defines its number of dimensions and the size of each dimension. The datatype of a tensor indicates the kind of data the tensor is holding.

We can access these properties using the .shape and .dtype attributes.

Here's a code example:

```Python
import tensorflow as tf

# Creating a constant tensor
tensor_example = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
```
The output of the above code will be:

```sh

Shape of tensor: (2, 3)
Data type of tensor: <dtype: 'int32'>
```
This output indicates that our tensor_example has a shape of 2x3, meaning it is a 2-dimensional tensor with sizes 2 and 3 in each dimension, respectively. Additionally, the tensor's datatype is int32, which specifies that the contained values are 32-bit integers.

## Converting Tensors to NumPy Arrays
TensorFlow tensors can be easily converted to NumPy arrays, which can be useful for printing, manipulation, or using NumPy functions. The .numpy() method allows us to convert a tensor to a NumPy array.

Here's how we can do it:

```Python
# Converting the tensor to a NumPy array
numpy_array = tensor_example.numpy()
print(f"NumPy array:\n{numpy_array}")
```

The output will be:

```sh

NumPy array:
[[1 2 3]
 [4 5 6]]
```

This demonstrates how easy and seamless it is to convert TensorFlow tensors to NumPy arrays, enabling us to leverage the extensive functionalities of NumPy alongside TensorFlow.

## Summary and Practice
In this lesson, our focus was understanding tensors and how to create and manipulate them using TensorFlow. By now you should understand what a tensor is, be able to create a tensor using TensorFlow and access and interpret their properties.

We've learnt the fundamentals, now it's time to get more hands-on exposure with tensors in the upcoming exercises. Practice will reinforce your understanding and equip you with the skills to use TensorFlow and tensors with ease. Your journey has just begun. Let's keep exploring!



## Discover TensorFlow Tensor Properties

In this task we show how to create a constant tensor using tf.constant(), examine its key properties like shape and data type, and finally how to convert it to a numpy array. No changes to the code are needed, simply execute it to see the results. This hands-on exercise reinforces your understanding of TensorFlow tensors.

## Tensor Properties: Shape and Type
In this task we show how to create a constant tensor using tf.constant(), examine its key properties like shape and data type, and finally how to convert it to a numpy array. No changes to the code are needed, simply execute it to see the results. This hands-on exercise reinforces your understanding of TensorFlow tensors.

```py
import tensorflow as tf

# Creating a constant tensor
tensor_example = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

# Converting the tensor to a NumPy array
numpy_array = tensor_example.numpy()
print(f"NumPy array:\n{numpy_array}")
```

## Debugging TensorFlow Tensor Creation
Building on your newfound skills with TensorFlow tensors, let's delve deeper now. Mastering the manipulation of tensors' shape and data type is a crucial skill in TensorFlow. This exercise will guide you in creating a tensor with a different shape and data type, emphasizing the impact of these properties on data representation.

When creating the Tensor, change its shape to (3, 2) and its data type to tf.float32. This modification will help you to appreciate TensorFlow's flexibility with data structures and understand the practical aspects of tensor manipulation.

```py
import tensorflow as tf

# TODO: Change the shape of this tensor to (3, 2) and its type to tf.float32
tensor_example = tf.constant([[1, 2],[ 3, 4], [5, 6]], dtype=tf.float32)

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)
```

## Creating a Tensor in TensorFlow

After becoming comfortable with the basics of creating and understanding tensors in TensorFlow, it's time to put your knowledge to the test with a slightly challenging task. You will encounter a piece of code designed to create a tensor, but something isn't right. A common error has slipped through, preventing the code from running as intended.

Your objective is to find and correct this error. Correcting mistakes like these will make you more adept at debugging and understanding TensorFlow's intricacies.

```py
import tensorflow as tf

# Correcting the dtype to float32 to match the floating-point values
tensor_example = tf.constant([[7.1, 8.2, 9.3], [10.4, 11.5, 12.6]], dtype=tf.float32)

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

```

## Mastering Tensor Creation Properties in TensorFlow

Following your progress through the basics of TensorFlow tensors, this practice will focus on an essential skill: creating a tensor. This step is critical for manipulating tensor properties, which underpins many TensorFlow operations.

Complete the missing code and remember, the datatype and the structure of the tensor are key aspects to consider.

```py
import tensorflow as tf

# Create a constant tensor
tensor_example = tf.constant([[7.1, 8.2, 9.3], [10.4, 11.5, 12.6]], dtype=tf.float32)

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

```

Following your exploration of TensorFlow tensors, this final practice consolidates your understanding by having you write code from scratch. Create a tensor representing a 3D object's dimensions, with values [2, 4, 6] for length, width, and height. Ensure you reveal the shape and data type of your tensor.

This task embraces what you've learned about creating tensors, specifying their data types, and investigating their properties. It offers a hands-on opportunity to apply these concepts in a practical setting.


```py
import tensorflow as tf

# Create a constant tensor with the values [2, 4, 6] representing a 3D object's dimensions
tensor_example = tf.constant([2, 4, 6], dtype=tf.int32)

# Display the shape of the tensor
print(f"Shape of tensor: {tensor_example.shape}")

# Display the data type of the tensor
print(f"Data type of tensor: {tensor_example.dtype}")

# Print the tensor
print(tensor_example)

```