# Lesson 5: Determinant and Linear Dependency

# Lesson Introduction

Welcome to our lesson on **Determinants and Linear Dependency**! These concepts are very important in machine learning.

In this lesson, we will cover:

- 📐 What a determinant is and how to calculate it.
- 🔗 What linear dependency means.
- 🧮 How to check for linear dependency using determinants.

By the end of this lesson, you’ll be ready to apply these concepts. Let’s dive in!

---

## Determinants in Linear Algebra

A determinant is a special number calculated from a square matrix (equal number of rows and columns). The determinant helps us understand properties, such as whether a matrix is invertible.

For a **2×2 matrix** \( A \):

\[
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
\]

The determinant, denoted as det(\( A \)), is calculated as:

\[
det(A) = a \cdot d - b \cdot c
\]

For larger matrices, the determinant is calculated using a recursive process involving **minors** and **cofactors**, which generalizes the concept of the \( 2×2 \) determinant. We won't go this deep into details in this course, as the calculation itself is not important for machine learning – the key is to understand the idea of the determinant.

---

## Determinant Calculation in Python

Here’s how to calculate the determinant of a \( 2×2 \) matrix in Python:

```python
import numpy as np

# Example matrix
m = np.array([[3, 8], [4, 6]])
print("Determinant of 2x2 matrix:", np.linalg.det(m))  # Determinant of 2x2 matrix: -14.0
```

In this code snippet, we use the `np.linalg.det` function to calculate the determinant using the formula.

---

## Concept of Linear Dependency

**Linear dependency** means one vector in a set can be written as a combination of the others. For example:

\[
v_1 = \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \quad v_2 = \begin{bmatrix} 2 \\ 4 \end{bmatrix}
\]

Here, \( v_2 \) is just twice \( v_1 \), showing the vectors are linearly dependent.

### Checking Linear Dependency

If any matrix row is linearly dependent on any other matrix row, or if any matrix column is linearly dependent on any other matrix column, such a matrix will always have a determinant of **0**.

Let's check it by constructing a matrix from linearly dependent \( v_1 \) and \( v_2 \):

```python
import numpy as np

matrix = np.array([
    [1, 2],
    [2, 4],
])

print(np.linalg.det(matrix))  # 0.0
```

This matrix has linearly dependent rows, so its determinant is zero.

---

## Practical Application of Determinants

One practical application of determinants is in solving systems of linear equations. Determinants can be used to find the inverse of a matrix, which is then applied in various algorithms, including those used in **computer graphics transformations** and **machine learning optimizations**.

Consider the following system of linear equations:

\[
\begin{aligned}
x + 2y &= 4 \\
2x + 4y &= 10
\end{aligned}
\]

And here is its matrix form:

\[
\begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix} \cdot \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 4 \\ 10 \end{bmatrix}
\]

If you try to solve this equation, you will see that it is not possible. It happens because the equations are linearly dependent. For large equation systems, it may not be so obvious, and calculating the matrix's determinant might be helpful in determining if the system has a solution.

---

## Lesson Summary

Great job! Let’s recap what we’ve learned:

- 📐 **What a determinant is** and how to calculate it for a \( 2×2 \) matrix.
- 🔗 The concept of **linear dependency** and its importance.
- 🧮 **How to check for linear dependency** using determinants in Python.

These concepts are foundational for advanced topics in linear algebra and machine learning. Now it’s time to put this knowledge into practice. In the next session, we’ll dive into hands-on exercises to apply what you’ve just learned.



## Calculate Determinant and Check for Linear Dependency

Here's the fixed and formatted Markdown version:  

# Hey there, Celestial Traveler! 🌌

Help complete the given code to calculate the determinant of the matrix:


\begin{bmatrix}
3 & 3 \\
4 & 4
\end{bmatrix}

Let’s see if the given matrix contains linear dependency.

---

### Let's Code! 🚀

```python
import numpy as np

matrix = [
    [3, 3],
    [4, 4]
]

# TODO: calculate and print the determinant of the matrix
```

Here’s the completed code to calculate the determinant of the matrix:

```python
import numpy as np

matrix = [
    [3, 3],
    [4, 4]
]

# Calculate and print the determinant of the matrix
determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", determinant)

# Check for linear dependency
if determinant == 0:
    print("The matrix contains linear dependency.")
else:
    print("The matrix does not contain linear dependency.")
```

### Explanation:
1. **`np.linalg.det(matrix)`**: Calculates the determinant of the matrix.
2. **`if determinant == 0`**: Checks if the determinant is zero, indicating linear dependency.

## Define a Matrix with Zero Determinant

Your task is to define a \( 2 \times 2 \) matrix with a zero determinant. Use your understanding of determinants to fill in the correct values. Make sure the product of the diagonal elements minus the product of the off-diagonal elements is zero.

You can do it!

```python
import numpy as np

# Define a 2x2 matrix with a zero determinant
matrix = [
    [1, 2],  # First row
    [2, 4]   # Second row
]

# Calculate and print the determinant
determinant = np.linalg.det(matrix)
print("Matrix:")
print(np.array(matrix))
print("Determinant of the matrix:", determinant)

# Verify if determinant is zero
if determinant == 0:
    print("The matrix has a zero determinant.")
else:
    print("The matrix does not have a zero determinant.")
```

### Output:
```plaintext
Matrix:
[[1 2]
 [2 4]]
Determinant of the matrix: 0.0
The matrix has a zero determinant.
```

### Explanation:
- The determinant of a \( 2 \times 2 \) matrix \([a, b; c, d]\) is calculated as:
  \[
  \text{det}(A) = a \cdot d - b \cdot c
  \]
- For the matrix \([
1, 2;
2, 4
]\), we have:
  \[
  \text{det}(A) = (1 \cdot 4) - (2 \cdot 2) = 4 - 4 = 0
  \]
- This confirms the determinant is zero, indicating linear dependency in the rows or columns.

## Find the Determinant of a 3x3 Matrix

Let's calculate the determinant of a given \( 3 \times 3 \) matrix. Its formula is much more complex than for a \( 2 \times 2 \) one, but with NumPy, it is just as easy. Complete the TODO comments and see the result!

```python
import numpy as np

# Define the matrix
matrix = np.array([[6, 1, 1], 
                   [4, -2, 5], 
                   [2, 8, 7]])

# Calculate the determinant using the `np.linalg.det` function
determinant = np.linalg.det(matrix)

# Print the determinant
print("Matrix:")
print(matrix)
print("Determinant of the matrix:", determinant)
```

### Output:
```plaintext
Matrix:
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
Determinant of the matrix: -306.0
```

### Explanation:
- The determinant of a \( 3 \times 3 \) matrix is calculated using the formula:
  \[
  \text{det}(A) = a(ei − fh) − b(di − fg) + c(dh − eg)
  \]
  where the matrix is:
  \[
  \begin{bmatrix}
  a & b & c \\
  d & e & f \\
  g & h & i
  \end{bmatrix}
  \]
- Using NumPy's `np.linalg.det`, the computation is done efficiently, and the determinant for the given matrix is \(-306\).
- A non-zero determinant indicates that the matrix is invertible and its rows/columns are linearly independent.

You're on a roll, Space Explorer!

You are given a system of linear equations represented as a matrix. Your task is to determine if the system is solvable by calculating the determinant of this matrix. If the determinant is zero, print "The system is non-solvable."

Let's solve this puzzle!

import numpy as np

# Large system of equations represented as a matrix
matrix = [
    [3, 4, 2],
    [2, 1, 4],
    [1, 2, 3]
]

# Calculate the determinant

# TODO: Check if the system is solvable
if ____:
    # TODO: print the verdict
else:
    # TODO: print the verdict

Here’s the completed code in markdown format, along with the logic to determine if the system of equations is solvable:

```python
import numpy as np

# Large system of equations represented as a matrix
matrix = [
    [3, 4, 2],
    [2, 1, 4],
    [1, 2, 3]
]

# Calculate the determinant
det = np.linalg.det(matrix)

# Check if the system is solvable
if det == 0:
    print("The system is non-solvable.")
else:
    print("The system is solvable.")
```

### Explanation:
1. **Calculate the determinant**:
   - `np.linalg.det(matrix)` computes the determinant of the given matrix.

2. **Check the determinant**:
   - If the determinant is `0`, the system is non-solvable (dependent or inconsistent equations).
   - If the determinant is non-zero, the system is solvable.

### Output:
For the given matrix:
```python
matrix = [
    [3, 4, 2],
    [2, 1, 4],
    [1, 2, 3]
]
```

#### Result:
```plaintext
The system is solvable.
```