# Lesson 1: Basics of Vectors and Matrices

```markdown
# Lesson Introduction

Welcome to this exciting course path! This path focuses on teaching math concepts that are important for machine learning. Note that this path assumes you have basic knowledge of the Python programming language. If needed, you can use our **Introduction to Programming in Python** course path to gain or solidify this knowledge.

## Welcome to Our Lesson on Vectors and Matrices!

In this lesson, we'll explore:
- What vectors and matrices are
- Why they're important in machine learning
- How to create and work with them in Python

By the end of this lesson, you'll understand how to define, display, and interpret vectors and matrices. Let's get started!

---

## Concept: Vector

Imagine you have a list of your favorite ice cream flavors: `["vanilla", "chocolate", "strawberry"]`. A vector is similar, but it contains numbers. For example, a vector could look like this: `[1, 2, 3]`.

### Definition of a Vector
A vector is a **one-dimensional array** of numbers:
- **Row vector**: A single row of numbers.
- **Column vector**: A single column of numbers.

#### Row Vector Example:
```plaintext
[1, 2, 3]
```

#### Column Vector Example:
```plaintext
[
 [1]
 [2]
 [3]
]
```

While they look similar, row and column vectors are treated differently in mathematical operations, so distinguishing between them is important.

### Creating and Displaying Vectors in Python

#### Creating a Row Vector:
```python
import numpy as np

# Create a row vector
row_vector = np.array([1, 2, 3])

# Display the vector
print("Row Vector:", row_vector)  # Output: Row Vector: [1 2 3]
```

#### Creating a Column Vector:
```python
import numpy as np

# Create a column vector
column_vector = np.array([
    [1],
    [2],
    [3]
])

# Display the vector
print("Column Vector:\n", column_vector)  # Output: Column Vector: [[1] [2] [3]]
```

---

## Concept: Matrix

A matrix is a **2D grid** of numbers, often used to represent data. For example, consider a class of students and their scores in three subjects: Math, Science, and English. A matrix could store these scores:

### Example of a Matrix:
```plaintext
[
 [95, 88, 92],
 [85, 90, 87],
 [78, 85, 80]
]
```

- Rows could represent students.
- Columns could represent subjects.

### Creating and Displaying a Matrix in Python
```python
import numpy as np

# Create a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Display the matrix
print("Matrix:\n", matrix)  # Output: [[1 2 3] [4 5 6] [7 8 9]]
```

---

## Getting Dimensions in Python

### Vectors:
For vectors, you can determine their size as follows:

#### Length of a Row Vector:
```python
row_vector = np.array([1, 2, 3])
print("Length of the row vector:", len(row_vector))  
# Output: Length of the row vector: 3
```

#### Length of a Column Vector:
```python
column_vector = np.array([
    [1],
    [2],
    [3]
])
print("Number of rows in the column vector:", column_vector.shape[0])  # Output: 3
```

### Matrices:
To determine the dimensions of a matrix:
- **Rows**: `matrix.shape[0]`
- **Columns**: `matrix.shape[1]`

#### Example:
```python
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Number of rows
print("Number of rows:", matrix.shape[0])  # Output: 3

# Number of columns
print("Number of columns:", matrix.shape[1])  # Output: 3
```

---

## Lesson Summary

To sum up, we’ve covered:
- **Vectors**: One-dimensional arrays (row or column).
- **Matrices**: Two-dimensional grids.
- How to create, display, and analyze vectors and matrices using `numpy`.

These concepts form the foundation of linear algebra in machine learning. Now it’s time to practice! Dive into the exercises to reinforce your understanding.
```

## Vectors and Matrices in Python

Hey there, Space Explorer! Want to see how vectors and matrices work in Python? The given code shows you how to create and display a row vector, a column vector, and a matrix using numpy. Click Run to see them in action!

import numpy as np

# Let's create and display vectors and matrices to see how it works

# Creating a row vector
row_vector = np.array([1, 2, 3])

# Creating a column vector
column_vector = np.array([
    [1],
    [2],
    [3]
])

# Creating a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Displaying the vectors and matrix
print("Row Vector:", row_vector)  # Output: Row Vector: [1 2 3]
print("Column Vector:\n", column_vector)  # Output: Column Vector: [[1] [2] [3]]
print("Matrix:\n", matrix)  # Output: Matrix: [[1 2 3] [4 5 6] [7 8 9]]


Here's a breakdown of how the code works, with some enhancements to make it even more interactive for your journey as a "Space Explorer"! 🚀

---

### Code Explanation

1. **Row Vector**:
   - A row vector is a one-dimensional array where all elements are aligned in a single row.
   - Created using `np.array([1, 2, 3])`.

2. **Column Vector**:
   - A column vector is a two-dimensional array where elements are aligned in a single column.
   - Created by wrapping each element in its own sub-array using `np.array([[1], [2], [3]])`.

3. **Matrix**:
   - A matrix is a 2D array with rows and columns.
   - Created using `np.array()` with a nested list representing rows.

4. **Displaying Results**:
   - The `print()` function displays each vector and matrix. Newlines (`\n`) are added to organize the output.

---

### Enhanced Code Example

```python
import numpy as np

# Create a row vector
row_vector = np.array([1, 2, 3])

# Create a column vector
column_vector = np.array([
    [1],
    [2],
    [3]
])

# Create a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Display the vectors and matrix
print("🚀 Row Vector:")
print(row_vector)  # Output: [1 2 3]

print("\n🌌 Column Vector:")
print(column_vector)  # Output: [[1] [2] [3]]

print("\n✨ Matrix:")
print(matrix)  # Output: [[1 2 3] [4 5 6] [7 8 9]]

# Additional fun: Shape of each structure
print("\n📏 Shapes:")
print("Row Vector Shape:", row_vector.shape)  # Output: (3,)
print("Column Vector Shape:", column_vector.shape)  # Output: (3, 1)
print("Matrix Shape:", matrix.shape)  # Output: (3, 3)
```

---

### Enhanced Output

```plaintext
🚀 Row Vector:
[1 2 3]

🌌 Column Vector:
[[1]
 [2]
 [3]]

✨ Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

📏 Shapes:
Row Vector Shape: (3,)
Column Vector Shape: (3, 1)
Matrix Shape: (3, 3)
```

---

### Key Insights

- **Shapes**:
  - Row vector is one-dimensional (`(3,)`).
  - Column vector is two-dimensional (`(3, 1)`).
  - Matrix is two-dimensional (`(3, 3)`).

This code demonstrates how to manipulate basic vector and matrix structures in Python using NumPy. Perfect for starting your cosmic journey into linear algebra! 🌟

## Modify the Column Vector

Space Explorer, let's make a small change to the code! Modify the column_vector to have four elements instead of three. This will help you practice working with column vectors and understand their structure better. Go ahead and give it a try!

import numpy as np

# Creating and displaying a column vector
column_vector = np.array([
   [7],
   [8],
   [9]
])
print("Column Vector:\n", column_vector)  # Output: Column Vector: [[7] [8] [9]]

Here's the modified code with a column vector containing four elements:

```python
import numpy as np

# Creating and displaying a column vector with four elements
column_vector = np.array([
   [7],
   [8],
   [9],
   [10]  # Added the fourth element
])

print("Column Vector:\n", column_vector)  # Output: Column Vector: [[7] [8] [9] [10]]
```

### Explanation:
- Added an additional row `[10]` to the column vector.
- The structure remains the same, with each element in its own row. This preserves the column vector format.

## Fix the Matrix

Great job learning about vectors and matrices! Now, there's a small bug in the provided code. Your task is to find and fix the issue to ensure it runs correctly and displays the expected output for each vector and the matrix. Good luck!

import numpy as np

# Creating and displaying a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
    [7, 8, 9]
])
print("Matrix:\n", matrix)  # Output: Matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Here's the corrected code with the fix:

```python
import numpy as np

# Creating and displaying a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],  # Added a missing comma to separate rows
    [7, 8, 9]
])
print("Matrix:\n", matrix)  # Output: Matrix: [[1 2 3] [4 5 6] [7 8 9]]
```

### Fix Explanation:
- The error in the code was a **missing comma** between the second (`[4, 5, 6]`) and third (`[7, 8, 9]`) rows of the matrix.
- Without the comma, Python interprets it as a syntax error because the rows aren't properly separated. Adding the comma resolves the issue.

### Expected Output:
```
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
```


## Defining the Matrix

Hello, Space Explorer!

Imagine you have a data about your spendings on different categories in weekends. The data is in the comments in the code. Your goal is to define a matrix to store this data, and to print it.

You got this!

import numpy as np 

# Day: Sat, Sun
# Food: 3, 4
# Transport: 1, 0
# Entertainment: 0, 5


## Find the Dimensions of a Matrix

## Creating a 3D Matrix from Two 2x2 Matrices