# Lesson 3: Basic Matrix Operations

Here's your text, fixed and formatted in Markdown for better readability:

---

# Lesson Introduction

In this lesson, we're diving into **basic matrix operations** used in machine learning. Understanding matrix operations is crucial because they underpin many algorithms in this field.

Today's goal is to learn **matrix addition** and **scalar multiplication**. By the end, you'll be able to add two matrices and multiply a matrix by a scalar using Python and NumPy.

---

## Matrix Addition: Definition and Real-Life Analogy

Matrix addition involves adding corresponding elements from two matrices. Imagine you have two grids of numbers and want to create a new grid where each number is the sum of the corresponding numbers from the original grids.

Think of each matrix as a seating chart for two classrooms. Adding the matrices is like finding the total number of students in the same seats in both charts.

---

## Matrix Addition: Code Explanation

To add two matrices, they must have the same dimensions. Here's how you can do it in Python with NumPy:

```python
import numpy as np

# Example matrices
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[7, 8, 9], [10, 11, 12]])

# Adding matrices
result = m1 + m2
print("Matrix Addition:\n", result)
```

**Output:**

```
Matrix Addition:
[[ 8 10 12]
 [14 16 18]]
```

### Explanation:
1. `np.array()` creates NumPy arrays from the provided lists.
2. `m1 + m2` adds the corresponding elements of `m1` and `m2`.

This sums elements at the same positions in both matrices to form a new matrix. Notice the `\n` in the print statement—it’s a special symbol for a new line.

---

## Practical Example

Suppose you manage inventory for two warehouses. Each warehouse has a matrix representing the quantity of different products in different sections. By adding the two matrices, you can find the total quantity of each product across both warehouses.

```python
import numpy as np

# Warehouse 1 inventory
warehouse1 = np.array([[10, 20, 30], [40, 50, 60]])

# Warehouse 2 inventory
warehouse2 = np.array([[5, 15, 25], [35, 45, 55]])

# Total inventory
total_inventory = warehouse1 + warehouse2
print("Total Inventory:\n", total_inventory)
```

**Output:**

```
Total Inventory:
[[ 15  35  55]
 [ 75  95 115]]
```

---

## Scalar Multiplication: Definition and Real-Life Analogy

Scalar multiplication involves multiplying every element in a matrix by a single number (scalar). Imagine you have a grid of numbers and want to adjust each number by multiplying it with another number.

It's like you have a collection of prices and want to apply a discount or markup uniformly. The scalar would be the discount or markup percentage.

---

## Scalar Multiplication: Code Explanation

Here’s how to perform scalar multiplication in Python with NumPy:

```python
import numpy as np

# Example matrix and scalar
m1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

# Scalar multiplication
result = scalar * m1
print("Scalar Matrix Multiplication:\n", result)
```

**Output:**

```
Scalar Matrix Multiplication:
[[ 2  4  6]
 [ 8 10 12]]
```

### Explanation:
- `scalar * m1` multiplies each matrix element by the scalar.
- This produces a new matrix where each element is scaled by the scalar value.

---

## Practical Example

Suppose you have a matrix representing the monthly salaries of employees in different departments. If you want to give everyone a 10% raise, you can use scalar multiplication with a scalar of `1.10`.

```python
import numpy as np

# Original salaries
salaries = np.array([[3000, 4000, 5000], [6000, 7000, 8000]])

# Scalar for 10% raise
raise_factor = 1.10

# Adjusted salaries
adjusted_salaries = raise_factor * salaries
print("Adjusted Salaries:\n", adjusted_salaries)
```

**Output:**

```
Adjusted Salaries:
[[3300. 4400. 5500.]
 [6600. 7700. 8800.]]
```

---

# Lesson Summary

We explored the basics of matrix operations, focusing on **matrix addition** and **scalar multiplication**. These operations are building blocks for complex tasks in machine learning and data science.

- **Matrix Addition**: Adding corresponding elements of two matrices with the same dimensions.  
- **Scalar Multiplication**: Multiplying every element of a matrix by a scalar.

Understanding these operations makes future lessons involving matrices easier to grasp.

Now it's time to move to the practice section. In the exercises, you'll get hands-on experience with matrix addition and scalar multiplication using NumPy. This will help solidify your understanding of the concepts and prepare you for advanced matrix operations. 

**Enjoy your coding journey!**

---

## Total Sales Calculation per Product Using Matrix Addition

Imagine you manage sales teams in two different regions, each represented by a matrix where rows correspond to different products and columns to quarterly sales figures. Use matrix addition to find the combined total sales for each product by completing the provided code.

Let's get those totals!

import numpy as np

sales_region1 = np.array([
    [200, 150, 340],
    [400, 300, 500]
])

sales_region2 = np.array([
    [150, 200, 210],
    [500, 400, 300]
])

# TODO: Find and print the total sales across regions per product

Here’s the completed Python code to calculate and print the total sales across regions for each product:

```python
import numpy as np

# Sales matrices for two regions
sales_region1 = np.array([
    [200, 150, 340],
    [400, 300, 500]
])

sales_region2 = np.array([
    [150, 200, 210],
    [500, 400, 300]
])

# Find and print the total sales across regions per product
total_sales = sales_region1 + sales_region2
print("Total Sales Across Regions:\n", total_sales)
```

### Explanation:
1. **Matrix Addition**: The `+` operator adds the corresponding elements of `sales_region1` and `sales_region2`.
2. **Result**: The resulting matrix represents the total quarterly sales for each product across both regions.

### Output:
```
Total Sales Across Regions:
[[ 350  350  550]
 [ 900  700  800]]
``` 

This shows the combined sales figures for each product in all quarters.

## Adjust Monthly Budgets by Percentage Increase

Space Wanderer, you have a matrix representing monthly budgets for different departments. Due to new policies, you need to give each budget a 5% boost by multiplying it by 1.05. Complete the task by updating the budget matrix using numpy.

Let's code!

import numpy as np

budgets = np.array([[1000, 1500, 2000], [1200, 1600, 1800]])
# TODO: Adjust the budgets increasing them by 5% using numpy and print it

Here’s the completed Python code to adjust the budgets by increasing them by 5%:

```python
import numpy as np

# Original budgets matrix
budgets = np.array([[1000, 1500, 2000], [1200, 1600, 1800]])

# Adjust the budgets by increasing them by 5%
adjusted_budgets = budgets * 1.05

# Print the adjusted budgets
print("Adjusted Budgets:\n", adjusted_budgets)
```

### Explanation:
1. **Matrix Multiplication**: The `* 1.05` operation multiplies each element of the `budgets` matrix by the scalar `1.05`, representing a 5% increase.
2. **Result**: This produces a new matrix with the updated budgets.

### Output:
```
Adjusted Budgets:
[[1050. 1575. 2100.]
 [1260. 1680. 1890.]]
``` 

Each budget is now increased by 5%.

## Calculating Average Daily Temperatures

Hey, Celestial Traveler!

Imagine you have temperature data for two cities over multiple weeks, stored in matrices. Your mission is to calculate the average daily temperatures for all the presented week across both cities. First, combine the matrices by adding them. Then, scale the result by multiplying by 1/2 to get the average. Complete the code to make this happen.

Let's get started!

import numpy as np

# Temperature data for two cities over a week
city1_temps = np.array([
    [30, 32, 31, 29, 28, 27, 26],
    [25, 27, 26, 24, 23, 22, 21]
])

city2_temps = np.array([
    [28, 30, 29, 27, 26, 25, 24],
    [23, 25, 24, 22, 21, 20, 19]
])

# TODO: Combine temperature data for both cities
combined_temps = # TODO

# TODO: Calculate the average temperature
average_temps = # TODO

print("Average Daily Temperatures:\n", average_temps)

Here’s the completed Python code to calculate the average daily temperatures across both cities:

```python
import numpy as np

# Temperature data for two cities over a week
city1_temps = np.array([
    [30, 32, 31, 29, 28, 27, 26],
    [25, 27, 26, 24, 23, 22, 21]
])

city2_temps = np.array([
    [28, 30, 29, 27, 26, 25, 24],
    [23, 25, 24, 22, 21, 20, 19]
])

# Combine temperature data for both cities
combined_temps = city1_temps + city2_temps

# Calculate the average temperature
average_temps = combined_temps * 0.5

print("Average Daily Temperatures:\n", average_temps)
```

### Explanation:
1. **Matrix Addition**: `city1_temps + city2_temps` adds the corresponding elements of the two matrices to combine the temperatures for both cities.
2. **Scaling by 0.5**: Multiplying the combined matrix by `0.5` calculates the average daily temperatures.

### Output:
```
Average Daily Temperatures:
[[29. 31. 30. 28. 27. 26. 25.]
 [24. 26. 25. 23. 22. 21. 20.]]
```

This gives the average temperatures for each day across both cities.

## Exploring the Transposition

Great! One of the things that you can do with matrices is transpose them. It is used in solving systems of linear equations. The transposed matrix is simply the same matrix, but with columns and rows swapped. You are given a matrix and the numpy library to assist you. Use the np.transpose function to transpose the matrix and see the result!

Let's explore the mysteries of linear algebra!

import numpy as np

# Example matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# TODO: Transpose the matrix using np.transpose function and display the result
# Hint: syntax is transposed_matrix = np.transpose(original_matrix)


Here’s the completed Python code to transpose the matrix:

```python
import numpy as np

# Example matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Transpose the matrix using np.transpose
transposed_matrix = np.transpose(matrix)

# Display the result
print("Original Matrix:\n", matrix)
print("Transposed Matrix:\n", transposed_matrix)
```

### Explanation:
1. **Transpose Operation**: `np.transpose(matrix)` swaps the rows and columns of the matrix.
2. **Result**: The columns of the original matrix become the rows in the transposed matrix.

### Output:
```
Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]
```

This shows the matrix in its transposed form, useful in various linear algebra applications.